### ISSUE TITLE
"Sonstiger Bezug und Tätigkeiten"  combination of two different types of entities - Display problems

### ISSUE THREAD

**Issue by MRWien** [acdh-oeaw/viecpro-backend-devops#110]
See also #109 with the same problem, but the other way around:

Person-Person-relations are shown perfectly, but of the labeltyp „Sonstige/r Funktion, Amtsinhabe und Beruf“ only the year is shown.

**Comment by MRWien** [comment]
@sennierer: The problem for "Sonstiger Bezug und Tätigkeiten" has been solved as we deleted the Person-Person Relation "Tätigkeiten für ausländische Höfe" by moving the information to the Label type "Sonstige/r Funktion, Amtsinhabe und Beruf". 

NOW the display of label types with years must be enabled.

**Comment by sennierer** [comment]
add date parsing to the labels to get ISO date column in the labels

**Comment by sennierer** [comment]
3 columns; "Bezug", "Beginn", "Ende"
